### ISSUE TITLE
Extension/Resuse Documentation

### ISSUE THREAD

**Issue by wakeless** [guzzle/command#27]
I'm trying to use this functionality as a basis for an API library.

Is there documentation for the best way to use/implement it? IE. ```new CurrindaAPIService``` which sets up all endpoints etc?

**Comment by jeremeamia** [comment]
There are no docs other than the README (which is out of date at the moment) at this time. I'll be thinking of how I want to address this going forward. This is a known issue, so I'm going to close this.
