### ISSUE TITLE
Is this compatible with Guzzle 5.1, 5.2, 5.3?

### ISSUE THREAD

**Issue by jwcobb** [guzzle/command#28]
If so can we get a composer.json update and a version bump? Anyone using guzzle-services which requires this seems to be stuck using Guzzle ~5.0

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by GrahamCampbell** [comment]
`~5.0` DOES NOT mean 5.x. Please read composer's docs.

**Comment by GrahamCampbell** [comment]
`~5.0` does NOT mean 5.0.x. Please read composer's docs.

**Comment by jwcobb** [comment]
You're right. Been debugging all day and brain fart on my part. Sorry to waste your time.
