### ISSUE TITLE
guzzle 6 requirements problem

### ISSUE THREAD

**Issue by rfussien** [guzzle/command#29]
Hello,

I'm trying to use guzzle/guzzle-services with guzzle 6, but the fact that guzzle/guzzle-services require guzzle/command and that guzzle command require guzzle "~5.0" makes it complicate (impossible) and I get stuck with guzzle 5.3.

How to reproduce:
$ composer require guzzlehttp/guzzle
Using version ^6.1 for guzzlehttp/guzzle
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing guzzlehttp/promises (1.0.2)
    Downloading: 100%

  - Installing psr/http-message (1.0)
    Downloading: 100%

  - Installing guzzlehttp/psr7 (1.2.0)
    Downloading: 100%

  - Installing guzzlehttp/guzzle (6.1.0)
    Downloading: 100%

Writing lock file
Generating autoload files

$ composer require guzzlehttp/guzzle-services
Using version ^0.5.0 for guzzlehttp/guzzle-services
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - guzzlehttp/command 0.7.1 requires guzzlehttp/guzzle ~5.0 -> no matching package found.
    - guzzlehttp/command 0.7.0 requires guzzlehttp/guzzle ~5.0 -> no matching package found.
    - guzzlehttp/guzzle-services 0.5.0 requires guzzlehttp/command 0.7.* -> satisfiable by guzzlehttp/command[0.7.0, 0.7.1].
    - Installation request for guzzlehttp/guzzle-services ^0.5.0 -> satisfiable by guzzlehttp/guzzle-services[0.5.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

Thanks in advance

**Comment by GrahamCampbell** [comment]
Yes. This doesn;t work on guzzle 6.

**Comment by GrahamCampbell** [comment]
As clearly shown: https://github.com/guzzle/command/blob/master/composer.json#L14.

**Comment by jeremeamia** [comment]
I'm working on upgrading this package to use Guzzle 6. guzzle-services will need upgrades as well. I will open up PRs when it's ready for a look.

**Comment by rfussien** [comment]
Great news. Thanks
