### ISSUE TITLE
How to migrate from 0.8 to 0.9?

### ISSUE THREAD

**Issue by 2ndGAB** [guzzle/command#36]
Hello,
Could you please explain a bit how to migrate from 0.8 to 0.9 to replace Event system please?

**EDIT**
I suppose I can find the answer [here](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md)

**Comment by Konafets** [comment]
Did the transition guide you mentioned helped you to get it done?

**Comment by 2ndGAB** [comment]
@Konafets, in fact I didn't have time to try it.

**Comment by 2ndGAB** [comment]
Hi @Konafets,

I come back to this subject as I now have to migrate a Guzzle 5 code to version 6.
The official dev team has no time at the moment but I need to move to a new PHP 7 server!

So I wondered if you could help me to switch from the Event system to the new Middleware.

My repository is [here](https://github.com/SecondGuide/sitra-tourisme)

It's a private one so I need to send you an invitation link.

**Comment by Konafets** [comment]
Do you using Guzzle and just Command or also Guzzle Services?

**Comment by 2ndGAB** [comment]
I use Guzzle and Guzzle command.

In AuthenticationSubscriber.php:

    use GuzzleHttp\Command\Event\InitEvent;
    use GuzzleHttp\Command\Event\PreparedEvent;
    use GuzzleHttp\Event\SubscriberInterface;

In ObjectsGlobalConfigSubscriber.php:

    use GuzzleHttp\Command\Event\InitEvent;
    use GuzzleHttp\Event\SubscriberInterface;

In Client.php, my problem is to replace the old events `onInit` and `onPrepare` and the `SubscriberInterface`

    ....
        $this->getEmitter()->attach(
            new AuthenticationSubscriber($description, $this->config, $this->getHttpClient())
        );

        $this->getEmitter()->attach(
            new ObjectsGlobalConfigSubscriber($description, $this->config)
        );
   ...

**Comment by Konafets** [comment]
I would consider that two days of work. Do you have a deadline? I think I can fit this into the next days before 27.12. I am on vaccation from 28.12. till 9.1. w/o internet connection. So from my side it could be done this year or next.

Tell me what you would give for two days work and I tell you if this works for me :-)
