### ISSUE TITLE
Exception "CommandClientException" returns code 0 instead of the HTTP error code

### ISSUE THREAD

**Issue by aand18** [guzzle/command#39]
Example: server replies to my request with a code 409 HTTP error. 
The following code prints 0 instead of 409.

```
try {    
   $response = $guzzleClient->execute($command);  
} catch (\GuzzleHttp\Command\Exception\CommandClientException $e) {  
    echo $e->getCode();
}
```

For example \GuzzleHttp\Exception\ClientException 's code is the HTTP code.
Am I missing something?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Yes, this is the correct behaviour. Exception codes are not related to http codes.
